### ISSUE TITLE
Use Gutenberg or Cobalt for the site

### ISSUE THREAD

**Issue by sendilkumarn** [rustwasm/rustwasm.github.io#11]
It would be interesting project to convert this site from Jekyll into something like Gutenberg or Cobalt and also redesign the site slightly to make it even more awesome

**Comment by fitzgen** [comment]
Jekyll Just Works(tm) and has easy integration with GitHub pages -- is it worth fixing something that isn't broken?

**Comment by sendilkumarn** [comment]
Just wanted to be in rust world 😜

**Comment by alexcrichton** [comment]
I'm gonna close this for now because we're still wrangling content much less what to generate the content with!
