### ISSUE TITLE
The build.sh is not work, doc's link is 404 page

### ISSUE THREAD

**Issue by Rivsen** [rustwasm/rustwasm.github.io#42]
### Describe the Bug

In page [`docs.html`](https://rustwasm.github.io/docs.html), all the doc's link is broken, targeted to 404 page.

### Steps to Reproduce

1. Open [`docs.html`](https://rustwasm.github.io/docs.html)
2. Click on `The Rust Wasm Book`
3. See error

### Expected Behavior

Open the rust wasm book page.

### Actual Behavior

I look around the source code, and find a `build.sh` to generate all the books under `docs/`, but the website not work like the shell's behavior.

### Additional Context

None yet.

**Comment by alexcrichton** [comment]
Should be fixed now!
