### ISSUE TITLE
Broken link to `wasm-bindgen` guilde.

### ISSUE THREAD

**Issue by cldershem** [rustwasm/rustwasm.github.io#50]
### Describe the Bug

Link to [`wasm-bindgen` guide](https://rustwasm.github.io/docs/wasm-bindgen/) is broken. It's linked to from the [learn/docs section](https://rustwasm.github.io/docs.html) of the site. It is also in the header of the [unpublished guide](https://rustwasm.github.io/wasm-bindgen/examples/webgl.html) which is the first google result a lot of times.

**Comment by alexcrichton** [comment]
Thanks for the report! Should be fixed now although may take a few more minutes for caches to get cleared
