### ISSUE TITLE
CI hasn't been run

### ISSUE THREAD

**Issue by elpiel** [rustwasm/rustwasm.github.io#61]
### Describe the Bug

The homepage of the [rustwasm.github.io](https://github.com/rustwasm/rustwasm.github.io) still shows version 0.10.0 (while 0.10.3 is the latest) as the latest and hasn't been updated since 9th of July 2021

Also, no github action seems to be triggered to update the website

**Comment by bergey** [comment]
@daxpedda It looks like the [Github Action for this repo](https://github.com/rustwasm/rustwasm.github.io/blob/src/ci/build.sh#L16) builds & deploys the (currently outdated) release guides from the most recent tagged commits of https://github.com/rustwasm/wasm-pack & https://github.com/rustwasm/wasm-bindgen.  I ran the [tag command](https://github.com/rustwasm/rustwasm.github.io/blob/src/ci/build.sh#L16) `git describe --abbrev=0 --tags` in those repos, and the tags match the releases on crates.io.  

Do you have access to Github Settings in this repo?  If you can reenable Actions and kick one off manually, I think that might be enough to update the website.  Or if there are errors in the GH Action, I'll take a look at those.

**Comment by daxpedda** [comment]
I see, thank you!

> Do you have access to Github Settings in this repo?

I don't, but I've requested it.

**Comment by daxpedda** [comment]
I did restart the CI and fixed the GitHub Actions used, but there seems to be some other issue with Ruby:
https://github.com/rustwasm/rustwasm.github.io/actions/runs/7857911355/job/21442294826

**Comment by bergey** [comment]
continued in https://github.com/rustwasm/rustwasm.github.io/pull/62

**Comment by daxpedda** [comment]
That seems to have worked, thank you very much!
